# Generated by Django 5.2.5 on 2025-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vminspectiontool',
            name='virtual_machine',
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Conectada'), ('disconnected', 'Desconectada')], default='disconnected', max_length=20, verbose_name='Status da Conexão'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='django_url',
            field=models.URLField(blank=True, verbose_name='URL do Django'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='mode',
            field=models.CharField(choices=[('TESTE', 'Teste'), ('PRODUCAO', 'Produção')], default='TESTE', max_length=20, verbose_name='Modo de Operação'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='source_type',
            field=models.CharField(choices=[('camera', 'Câmera'), ('pasta', 'Pasta de Imagens'), ('rtsp', 'Stream RTSP')], default='camera', max_length=20, verbose_name='Tipo de Fonte'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(choices=[('running', 'Rodando'), ('stopped', 'Parada'), ('error', 'Erro'), ('offline', 'Offline')], default='stopped', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='trigger_type',
            field=models.CharField(choices=[('continuous', 'Contínuo'), ('manual', 'Manual'), ('interval', 'Intervalo')], default='continuous', max_length=20, verbose_name='Tipo de Trigger'),
        ),
        migrations.AlterModelTable(
            name='virtualmachine',
            table=None,
        ),
        migrations.DeleteModel(
            name='VMHeartbeat',
        ),
        migrations.DeleteModel(
            name='VMInspectionTool',
        ),
    ]
