# Generated by Django 5.2.4 on 2025-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_vminspectiontool_virtual_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Endereço IP'),
        ),
    ]
