# Generated by Django 5.2.4 on 2025-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_virtualmachine_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='django_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL do Django'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL RTSP'),
        ),
    ]
