# Generated by Django 5.2.5 on 2025-08-23 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_toolkind_seed'),
    ]

    operations = [
        # ToolKind já foi criado na 0005_toolkind_seed
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Inspeção')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.virtualmachine', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['vm_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Ordem no Pipeline')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Tool')),
                ('type', models.CharField(choices=[('grayscale', 'Grayscale'), ('blur', 'Blur'), ('threshold', 'Threshold'), ('morphology', 'Morphology'), ('blob', 'Blob'), ('math', 'Math')], max_length=20, verbose_name='Tipo')),
                ('roi_x', models.IntegerField(default=0, verbose_name='ROI X')),
                ('roi_y', models.IntegerField(default=0, verbose_name='ROI Y')),
                ('roi_w', models.IntegerField(default=0, verbose_name='ROI Largura')),
                ('roi_h', models.IntegerField(default=0, verbose_name='ROI Altura')),
                ('inspec_pass_fail', models.BooleanField(default=False, verbose_name='Afeta Pass/Fail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.inspection', verbose_name='Inspeção')),
                ('tool_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tools', to='api.toolkind', verbose_name='Tipo (ToolKind)')),
            ],
            options={
                'verbose_name': 'Ferramenta de Inspeção',
                'verbose_name_plural': 'Ferramentas de Inspeção',
                'ordering': ['inspection_id', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrayscaleTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('luminance', 'Luminance'), ('average', 'Average'), ('weighted', 'Weighted')], default='luminance', max_length=20)),
                ('normalize', models.BooleanField(default=False)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grayscale', to='api.inspectiontool')),
            ],
        ),
        migrations.CreateModel(
            name='BlurTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('gaussian', 'Gaussian'), ('median', 'Median')], default='gaussian', max_length=20)),
                ('ksize', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('sigma', models.FloatField(default=0.0)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blur', to='api.inspectiontool')),
            ],
        ),
        migrations.CreateModel(
            name='BlobToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('th_max', models.IntegerField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('area_min', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('area_max', models.FloatField(default=1000000000000.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_area_test', models.BooleanField(default=False)),
                ('blob_count_test', models.BooleanField(default=False)),
                ('test_total_area_min', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('test_total_area_max', models.FloatField(default=1000000000000.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('test_blob_count_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('test_blob_count_max', models.IntegerField(default=1000000, validators=[django.core.validators.MinValueValidator(0)])),
                ('contour_chain', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('NONE', 'NONE'), ('TC89_L1', 'TC89_L1'), ('TC89_KCOS', 'TC89_KCOS')], default='SIMPLE', max_length=20)),
                ('approx_epsilon_ratio', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('polygon_max_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blob', to='api.inspectiontool')),
            ],
        ),
        migrations.CreateModel(
            name='MathTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, choices=[('area_ratio', 'Area Ratio'), ('blob_density', 'Blob Density'), ('custom_formula', 'Custom Formula')], max_length=30)),
                ('custom_formula', models.TextField(blank=True)),
                ('reference_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_math', to='api.inspectiontool')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='math', to='api.inspectiontool')),
            ],
        ),
        migrations.CreateModel(
            name='MorphologyTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('open', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shape', models.CharField(choices=[('ellipse', 'Ellipse'), ('rect', 'Rect'), ('cross', 'Cross')], default='ellipse', max_length=20)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morphology', to='api.inspectiontool')),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('binary', 'Binary'), ('range', 'Range'), ('otsu', 'Otsu')], default='binary', max_length=20)),
                ('th_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('th_max', models.IntegerField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='api.inspectiontool')),
            ],
        ),
    ]
