# Generated by Django 5.2.5 on 2025-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inspection_reference_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkind',
            name='category',
            field=models.CharField(choices=[('filter', 'Filtro'), ('analytic', 'Analítica'), ('math', 'Matemática')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='toolkind',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
