# Generated by Django 5.2.5 on 2025-09-12 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_inspectiontool_roi_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID do Ciclo')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('approved', models.BooleanField(db_index=True, default=False, verbose_name='Aprovado')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Duração (ms)')),
                ('frame', models.IntegerField(default=0, verbose_name='Número do Frame')),
                ('reprovadas', models.IntegerField(default=0, verbose_name='Total Reprovadas até o Frame')),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL da Imagem')),
                ('image_mime', models.CharField(blank=True, max_length=50, null=True, verbose_name='MIME da Imagem')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Largura da Imagem')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Altura da Imagem')),
                ('result_json', models.JSONField(default=dict, verbose_name='Resultado (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_results', to='api.virtualmachine', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Resultado de Inspeção',
                'verbose_name_plural': 'Resultados de Inspeção',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['vm', 'timestamp'], name='api_inspect_vm_id_726f35_idx'), models.Index(fields=['vm', 'approved', 'timestamp'], name='api_inspect_vm_id_5e585b_idx')],
            },
        ),
    ]
