# Generated by Django 5.2.5 on 2025-09-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inspectionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_batch_ms',
            field=models.IntegerField(default=500, verbose_name='Batch (ms)'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_batch_size',
            field=models.IntegerField(default=20, verbose_name='Batch Size'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_buffer_size',
            field=models.IntegerField(default=0, verbose_name='Buffer de Logging (RAM)'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_enabled',
            field=models.BooleanField(default=False, verbose_name='Logging Ativo'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_max_logs',
            field=models.IntegerField(default=1000, verbose_name='Máx. Logs'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_mode',
            field=models.CharField(default='keep_last', max_length=20, verbose_name='Modo de Logging'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logging_policy',
            field=models.CharField(default='ALL', max_length=20, verbose_name='Política de Logging'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='logs_count',
            field=models.IntegerField(default=0, verbose_name='Qtd. Logs em Disco'),
        ),
    ]
