# Generated by Django 5.2.5 on 2025-09-23 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_virtualmachine_logging_batch_ms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectiontool",
            name="type",
            field=models.CharField(
                choices=[
                    ("grayscale", "Grayscale"),
                    ("blur", "Blur"),
                    ("threshold", "Threshold"),
                    ("morphology", "Morphology"),
                    ("blob", "Blob"),
                    ("locate", "Locate"),
                    ("math", "Math"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="LocateToolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrow_p0_x", models.FloatField(default=0.0)),
                ("arrow_p0_y", models.FloatField(default=0.0)),
                ("arrow_p1_x", models.FloatField(default=0.0)),
                ("arrow_p1_y", models.FloatField(default=0.0)),
                ("threshold_mode", models.CharField(default="fixed", max_length=20)),
                ("th_min", models.FloatField(default=20.0)),
                ("th_max", models.FloatField(default=255.0)),
                ("adaptive_k", models.FloatField(default=1.0)),
                ("polaridade", models.CharField(default="any", max_length=20)),
                (
                    "max_edges",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("edge_select", models.CharField(default="strongest", max_length=30)),
                (
                    "smooth_ksize",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "grad_kernel",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("apply_transform", models.BooleanField(default=False)),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locate",
                        to="api.inspectiontool",
                    ),
                ),
            ],
        ),
    ]
