# Generated by Django 5.2.5 on 2025-09-23 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_inspectiontool_type_locatetoolconfig"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locatetoolconfig",
            old_name="th_min",
            new_name="threshold",
        ),
        migrations.RemoveField(
            model_name="locatetoolconfig",
            name="max_edges",
        ),
        migrations.RemoveField(
            model_name="locatetoolconfig",
            name="th_max",
        ),
    ]
