# Generated by Django 5.2.5 on 2025-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_toolkind_locate_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="locatetoolconfig",
            name="reference_A",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locatetoolconfig",
            name="reference_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locatetoolconfig",
            name="reference_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locatetoolconfig",
            name="rotate",
            field=models.BooleanField(default=False),
        ),
    ]
